name: Mac Build

on: [push]

jobs:
  build-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: for cpp 17
      run: gcc --version
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
 
